### ISSUE TITLE
updating the wallpaper always retrieves random image

### ISSUE THREAD

**Issue by christianrauch** [neffo/bing-wallpaper-gnome-extension#109]
The last update added the functionality to skip wallpapers forward/backward and also to set a random wallpaper.

Since this update, fetching the most recent wallpaper will always retrieve a random:

https://user-images.githubusercontent.com/8573621/120906078-5d4ce000-c64e-11eb-81ff-3f437627645c.mp4

**Comment by christianrauch** [comment]
Hm, it looks like this is just a UI issue. I clicked the "randomise" button (crossed arrows) once to get a random image but assumed that clicking "update now" would retrieve the most recent image.

I suggest that the "randomise" button randomises the image and the "update now" fetches the most recent image. Otherwise, both buttons would have the same functionality, and in this case the "randomise" button should be removed to avoid confusion.

**Comment by neffo** [comment]
Apologies, I guess the UI is a bit confusing. 'Refresh now' will force a refresh of the Bing data, and that's really all it should do.

I took a shortcut in implementing 'random' mode where it would trigger refresh of Bing on change, and manually refreshing Bing would trigger an image change. This is now fixed in #110 branch. I've also added a 'select current image' button. I'm just using media icons, so I hope they are somewhat self explanatory. I should probably create a wiki for documentation.
