### ISSUE TITLE
[BUG] partially loaded image is displayed

### ISSUE THREAD

**Issue by christianrauch** [neffo/bing-wallpaper-gnome-extension#145]
**Describe the bug**
A partially loaded image is displayed under some circumstances, e.g. on network loss or the shell is locking the screen, and a refresh will not update this image.

**Screenshots**
This is the partially downloaded image:

![20211218-MoonBeforeYule_EN-GB4058117703_UHD](https://user-images.githubusercontent.com/8573621/146646357-c373c010-59a4-4bbc-8f1c-e491dc000141.jpg)

The lower part of the image is cut off. This is better visible if shown externally with an image viewer, e.g. "Eye of GNOME" (eog).

**To Reproduce**
This happened to me a couple of times, but it's not directly reproducible. I think this happens when the wallpaper is updating and either the network is interrupted or the shell is doing something else, e.g. locking the screen.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Extension Version: 37
 - GNOME Version: 3.36

**Additional context**
I think the extension should verify (e.g. by a hashsum) that the image was downloaded correctly. At least there should be an option to refresh the image and download it again. Currently, refreshing will do nothing and keep the image broken. The only way to reload the image is to delete it manually form the wallpaper folder and refresh again.

**Comment by christianrauch** [comment]
Believe it or not, it just happened again after a restart:

![20211218-MoonBeforeYule_EN-GB4058117703_UHD](https://user-images.githubusercontent.com/8573621/146646972-90ad6113-3bb1-4ff8-92d9-e250e6f336a4.jpg)

**Comment by neffo** [comment]
Thanks for reporting this. This is something I've seen myself, so definitely confirmed. It's due to the way the extension saves each chunk of the file as it's received rather than waiting till it's complete (which should be fine for a ~5 to 10 mb file). It should also be possible to add a validity check as well as there is a hash in the JSON we receive from Bing. I will look into implementing both of these.

In the meantime, if you have these broken files you can either delete them in your file browser or via the in-extension image gallery. If it's a image that is missing/deleted it will be re-downloaded if you apply the image as wallpaper (selecting it through the menu back and forward buttons).

![image](https://user-images.githubusercontent.com/5569112/146661192-56b671d2-c66b-43e3-a89a-67c5c16cc23f.png)

**Comment by Spurlos** [comment]
This issue became major one for me, due to my internet connection deterioration (i'm in the part of Ukraine that is going thru war currently, and we have limit connectivity, ~1-2 mbit with 20-50% packet loss when congested). Almost all wallpapers only load partially, like 5-10% and then stop.

Can you merge [`7a7693d` (#144)](https://github.com/neffo/bing-wallpaper-gnome-extension/pull/144/commits/7a7693d5cc707babe7470c74d9a9dc7622b94a92) if its ready for prime time?

**Comment by neffo** [comment]
Yeah thanks for bug report, stay strong. ✌️

There's a few outstanding niggling issues I want to clear and I need to test, but shouldn't be too far away. If you drop the image resolution to 1080p, is it more reliable (image should be ~80% smaller)?
