### ISSUE TITLE
Version 39 not installing on Fedora 35

### ISSUE THREAD

**Issue by Sensei1304** [neffo/bing-wallpaper-gnome-extension#155]
![зображення](https://user-images.githubusercontent.com/51707592/159171310-d7cf6617-b8b7-43da-9e48-9cb1569732d6.png)

**Comment by neffo** [comment]
I can't reproduce, do you have any error description?

![Screenshot from 2022-03-21 09-26-49](https://user-images.githubusercontent.com/5569112/159191188-33a188d8-acdb-4df2-905e-0205054fedac.png)

**Comment by Sensei1304** [comment]
Restart indeed fixed it, thanks

**Comment by neffo** [comment]
Thanks for report and confirmation of fix.

**Comment by nathanael-naeri** [comment]
I came here to report the same thing (albeit on Ubuntu 20.04 w/ GNOME 3.36.8). After a manual update, the GNOME Extensions website displays ERROR in red like in the OP's picture, and the extension's indicator disappears from the top bar, all of which is fairly alarming if you don't know it comes back after a restart.

The error message in `/var/sys/syslog` if logging is enabled is perfectly clear, but it isn't surfaced in the GNOME Extensions website or in the extension itself:

```
Mar 24 22:16:37 hostname gnome-shell[1660]: JS ERROR: Extension [BingWallpaper@ineffable-gmail.com](mailto:BingWallpaper@ineffable-gmail.com): Error: A different version was loaded previously. You need to log out for changes to take effect.#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:343:52#012callback@resource:///org/gnome/shell/ui/extensionDownloader.js:234:39#012gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13
```

Can this behavior perhaps be documented in the README.md file? Or maybe in the About tab of the extension's settings, if it's more appropriate there? That might help new users who don't know about this GNOME quirk.

Also:

> GNOME should auto update extensions (on restart)

Never happens in my case

> but forcing an update can sometimes break things

Always happens in my case

**Comment by neffo** [comment]
Yeah, sorry the auto update functionality is in newer versions of GNOME (good to know people are still using 3.36 btw).

I'm not sure the best way to handle updating then, perhaps restart the shell through alt-f2, 'r' combo. We do have a mention in the description for the extension on EGO, but maybe not clear enough.

![Screenshot_20220325-084257.png](https://user-images.githubusercontent.com/5569112/160022191-9a59f977-c2db-4722-ac70-70d499d7c31e.png)

**Comment by nathanael-naeri** [comment]
Thank you for pointing that out, and for the super-fast reply. I probably read that sentence when I installed your extension, and tried to make a mental note of it, but I had very clearly forgotten about it when I updated the extension for the first time.

Maybe you could move that sentence to the first paragraph of the text, so that it appears on https://extensions.gnome.org/local, which is where the Upgrade button is located which leads to the red ERROR message? That would probably make it more visible how to fix the error.

![Screenshot from 2022-03-22 09-58-09](https://user-images.githubusercontent.com/17598546/160023405-f8f728ab-ecf8-4b4f-969b-6901614f8fdb.png)

Yes, still using GNOME 3.36. As Ubuntu 20.04 is an LTS, it is here to stay I'm afraid.

**Comment by neffo** [comment]
Great point on moving the comment. Will do.

Happy to support 3.36, I just don't have visibility of how many people are using it. Given it's the current LTS I aim to keep it supported, though so don't worry about that.
