### ISSUE TITLE
screen saver huge delays

### ISSUE THREAD

**Issue by ser** [neffo/bing-wallpaper-gnome-extension#35]
when i have this extension on, it sometimes takes a good few minutes to open screen after it is being locked by screen saver.

**Comment by neffo** [comment]
Hi @ser, thanks for reporting this. I am already looking into this issue. What you might be seeing is a full shell crash, I presume you are not running Fedora? 

I can tell you, I have been able to replicate it myself:
```
michael@ubuntupc:/var/crash$ ls core.1000.gnome-shell.* -lart
-rw------- 1 michael whoopsie 1880240128 Apr 11 17:59 core.1000.gnome-shell.2077
-rw------- 1 michael whoopsie 1779453952 Apr 12 16:46 core.1000.gnome-shell.2132
-rw------- 1 michael whoopsie 1608126464 Apr 14 20:11 core.1000.gnome-shell.2087
-rw------- 1 michael whoopsie 1650466816 Apr 16 11:45 core.1000.gnome-shell.2005
-rw------- 1 michael whoopsie 1268277248 Apr 16 13:56 core.1000.gnome-shell.29397
-rw------- 1 michael whoopsie 1437450240 Apr 17 20:17 core.1000.gnome-shell.3887
-rw------- 1 michael whoopsie 1526960128 Apr 17 20:20 core.1000.gnome-shell.5046
-rw------- 1 michael whoopsie  953438208 Apr 18 01:29 core.1000.gnome-shell.2032
-rw------- 1 michael whoopsie  897892352 Apr 18 01:29 core.1000.gnome-shell.4121
-rw------- 1 michael whoopsie 1298010112 Apr 19 00:30 core.1000.gnome-shell.3810
-rw------- 1 michael whoopsie  896143360 Apr 19 00:30 core.1000.gnome-shell.25932
-rw------- 1 michael whoopsie 1382768640 Apr 19 23:14 core.1000.gnome-shell.3855
```

And it seems to a problem in GNOME at this moment, see this [bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1489554). I'm not sure I have any mitigations at this time, if you are running Ubuntu you MIGHT have some luck with running LightDM instead of GDM with this specific issue (the returning from lock screen).

I'm not sure why precisely unlocking the screen causes a crash, although I've found out that all extensions are unloaded when the screen locks and reloaded when the screen is unlocked. (Which is why I suggested trying LightDM, if it's an option. But doing that has downsides...)

Please note this is affecting a number of extensions, and seems to be related to notifications (so it's possible any program that generates notifications might be able to trigger the crash). GDB output of the most recent crash below if you are curious:
```
Core was generated by `/usr/bin/gnome-shell'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  g_type_check_instance_cast (type_instance=0x56033fe442e0, iface_type=94571815926464) at ../../../../gobject/gtype.c:4057
4057	../../../../gobject/gtype.c: No such file or directory.
[Current thread is 1 (Thread 0x7fda6ae09ac0 (LWP 3855))]
(gdb) bt
#0  0x00007fda6a256de2 in g_type_check_instance_cast (type_instance=0x56033fe442e0, iface_type=94571815926464) at ../../../../gobject/gtype.c:4057
#1  0x00007fda679c2768 in st_label_set_text () at /usr/lib/gnome-shell/libst-1.0.so
#2  0x00007fda63eb3e18 in ffi_call_unix64 () at ../src/x86/unix64.S:76
#3  0x00007fda63eb387a in ffi_call (cif=cif@entry=0x56033957f478, fn=<optimised out>, rvalue=<optimised out>, rvalue@entry=0x7ffdcab8ac98, avalue=avalue@entry=0x7ffdcab8ab90) at ../src/x86/ffi64.c:525
#4  0x00007fda68f183c8 in gjs_invoke_c_function(JSContext*, Function*, JS::HandleObject, JS::HandleValueArray const&, mozilla::Maybe<JS::MutableHandle<JS::Value> >, GIArgument*) (context=context@entry=0x560337ac6c00, function=function@entry=0x56033957f460, obj=..., 
    obj@entry=..., args=..., js_rval=..., r_value=r_value@entry=0x0) at gi/function.cpp:1033
#5  0x00007fda68f19ca4 in function_call(JSContext*, unsigned int, JS::Value*) (context=0x560337ac6c00, js_argc=1, vp=0x7ffdcab8b038) at gi/function.cpp:1351
#6  0x00002b51b3ebb810 in  ()
#7  0x00007fd9c32adec0 in  ()
#8  0x00007ffdcab8b010 in  ()
#9  0x0000000000000000 in  ()
```

**Comment by ser** [comment]
Thanks a lot for this analysis, I wasn't aware of that bug in gnome. I also hope it will be fixed soon and I'll be able to use your fantastic extension again.

**Comment by neffo** [comment]
ser, if you can, could you try test the last git version?

I've ripped out all the notifications (they are a bit pointless anyway), so it will hopefully avoid triggering that particular bug. I may have introduced new bugs, but I haven't been able to reproduce the original bug in my testing.

**Comment by ser** [comment]
Hi, unfortunately today I also had to wait 6 minutes again. I am not able to say it is for 100% fault of your extension as I have them a few, but when I have yours disabled, I did not have to wait ever.

**Comment by neffo** [comment]
Ok, so that isn't what I was seeing after all. It was more like 20-30 seconds before the desktop became responsive again.

Do you mind letting me know which extensions, and distribution you are running?

**Comment by ser** [comment]
The list is long :)

```
ls $HOME/.local/share/gnome-shell/extensions
better-osd                                   extend-left-box@bondhu.paul.gmail.com        noannoyance@sindex.com               timepp@zagortenay333
BingWallpaper@ineffable-gmail.com            gnomehub@hschmidt.suse.com                   no-title-bar@franglais125.gmail.com  topIcons@adel.gadllah@gmail.com
bitcoin-markets@ottoallmendinger.github.com  harddiskled@bijidroid.gmail.com              overview-titles@naheel.com           weatherintheclock@JasonLG1979.github.io
clipboard-indicator@tudmotu.com              hide-shutdown-button@adrienpoupa.github.com  raisecovered@rliang.github.com
dash-to-panel@jderose9.github.com            KeepAwake@jepfa.de                           set-columns@maestroschan.fr
disable-ubuntu-dock@maestroschan.fr          lwsm@johannes.super-productivity.com         simplenetspeed@biji.extension
```

From those I had to turn off clipboard and wallpaper extensions, all the rest seem to work, better or worse, but at least not blocking screen saver for long minutes

**Comment by ser** [comment]
I have downloaded current master again and checking it out :)

**Comment by neffo** [comment]
Oh wow, I think it's safe to say you are a poweruser of Gnome! I'm running fewer extensions, but identical GNOME/Ubuntu version. Not sure this bug is fixed in 3.28 however.

I am still seeing intermittent crashes, but they don't appear to be coming from this extension. I'll try walk you through how I know this. You might want to find the culprit (it may be Bing Wallpaper in your case).

1. Turn on core dumps by adding this to /etc/security/limits.conf (replace <username> with your login): 
```
<username>         soft    core            unlimited
```
2. (Optional) Set default core dump location to be somewhere sensible in /etc/sysctl.d/99-sysctl.conf
```
kernel.core_pattern=/var/crash/core.%u.%e.%p
fs.suid_dumpable=0
```
(Might need to create this folder.)
3. Install debug symbols for the various GNOME libraries.
```
sudo apt-get install libgjs0g-dbgsym libglib2.0-0-dbgsym libglib2.0-bin-dbgsym \
libglib2.0-dev-bin-dbgsym libglib2.0-cil-dbgsym libffi-dev-dbgsym libmozjs-52-dev-dbgsym \
libst1-dbgsym gnome-shell-dbgsym
```
4. (Might have to reboot first.) Make it crash...
5.  Run gdb on the most recent core
```
gdb --core /var/crash/core.1000.gnome-shell.16168 /usr/bin/gnome-shell
```
6. Type 'bt' to get the backtrace
```
(gdb) bt
#0  0x00007f4145493de2 in g_type_check_instance_cast (type_instance=0x55666d8e2890, iface_type=93898325507456)
    at ../../../../gobject/gtype.c:4057
#1  0x00007f4142bff768 in st_label_set_text (label=0x556672d88220 [StLabel], text=0x55667c39be00 "N/A") at ../src/st/st-label.c:331
#2  0x00007f413f0f0e18 in ffi_call_unix64 () at ../src/x86/unix64.S:76
#3  0x00007f413f0f087a in ffi_call (cif=cif@entry=0x55666aa69078, fn=<optimised out>, rvalue=<optimised out>, 
    rvalue@entry=0x7ffe237a2fb8, avalue=avalue@entry=0x7ffe237a2eb0) at ../src/x86/ffi64.c:525
#4  0x00007f41441553c8 in gjs_invoke_c_function(JSContext*, Function*, JS::HandleObject, JS::HandleValueArray const&, mozilla::Maybe<JS::MutableHandle<JS::Value> >, GIArgument*) (context=context@entry=0x556668636650, function=function@entry=0x55666aa69060, obj=..., 
    obj@entry=..., args=..., js_rval=..., r_value=r_value@entry=0x0) at gi/function.cpp:1033
#5  0x00007f4144156ca4 in function_call(JSContext*, unsigned int, JS::Value*) (context=0x556668636650, js_argc=1, vp=0x7ffe237a3358)
    at gi/function.cpp:1351
#6  0x0000373d4344d810 in  ()
#7  0x00007f409ecf0040 in  ()
#8  0x00007ffe237a3330 in  ()
#9  0x0000000000000000 in  ()
```
7. The interesting line is # 1, the "N/A" there is actually what the label text is being set to, but heres the thing. So we can use that text to try find the culprit. There no "N/A" in my extension at all.
```
michael@ubuntupc:~/.local/share/gnome-shell/extensions$ fgrep "N/A" -r .
./freon@UshakovVasilii_Github.yahoo.com/extension.js:            return 'N/A';
./sensory-perception@HarlemSquirrel.github.io/extension.js:      this.statusLabel.set_text(_("N/A")); // Just in case
./sensory-perception@HarlemSquirrel.github.io/po/es.po:msgid "N/A"
./sensory-perception@HarlemSquirrel.github.io/po/nb.po:msgid "N/A"
./sensory-perception@HarlemSquirrel.github.io/po/tr.po:msgid "N/A"
./sensory-perception@HarlemSquirrel.github.io/po/zh_CN.po:msgid "N/A"
./sensory-perception@HarlemSquirrel.github.io/po/fr.po:msgid "N/A"
./sensory-perception@HarlemSquirrel.github.io/po/it.po:msgid "N/A"
./sensory-perception@HarlemSquirrel.github.io/po/gnome-shell-extension-sensors.pot:msgid "N/A"
./sensory-perception@HarlemSquirrel.github.io/po/de.po:msgid "N/A"
```

**Comment by ser** [comment]
Hi :)

I've just installed bionic and at first look it seems that all freezing problems gone! I will play for few more days and close this issue if things continue to work properly.

**Comment by ser** [comment]
I can confirm, ALL screen-unlock-related problems gone on current gnome shipped with bionic. Even my lovely clipboard extension works now!!!! 

In summary: if you have problems with screen unlocking, just upgrade to Shell 3.28.1 :) 

Thanks a lot Michael!

**Comment by neffo** [comment]
Great news. Thanks so much for your feedback!
