### ISSUE TITLE
Error while loading extension

### ISSUE THREAD

**Issue by mkaput** [neffo/bing-wallpaper-gnome-extension#7]
Hello!

Thanks for the useful extension, but unfortunately it crashes on startup on my machine:

```
gnome-shell[1565]: Extension "BingWallpaper@ineffable-gmail.com" had error: TypeError: BingWallpaperIndicator.stop is not a function
```

Fedora Workstation 26

**Comment by neffo** [comment]
Hi mkaput, this bug was fixed but the update is still in the review queue on the [extensions.gnome.org](https://extensions.gnome.org/review/) page. You are probably still using version 4.

In the meantime you can download the latest version (v6) zip file [https://neffo.github.io/BingWallpaper@ineffable-gmail.com.zip](https://neffo.github.io/BingWallpaper@ineffable-gmail.com.zip) and install via the Gnome Tweak Tool.

**Comment by mkaput** [comment]
Thanks for quick reply!

It works now ;)

**Comment by neffo** [comment]
No problem, thanks for using it and helping to improve it!
