### ISSUE TITLE
No wallpaper available

### ISSUE THREAD

**Issue by gleidson** [neffo/bing-wallpaper-gnome-extension#9]
After last update is not working. Every time show the message No wallpaper available.

![nowallpaperavailable](https://user-images.githubusercontent.com/26634/29054057-156a3eea-7bca-11e7-87ac-7a1565967e32.png)

Fedora 26
Gnome 3.24

**Comment by IvanTurgenev** [comment]
Same fedora 25

**Comment by neffo** [comment]
Ahh, this was due to the animated wallpaper on that day (rather than anything that broke with the extension). I have a fix in place for the next update (version 8), but it's not yet published on extensions.gnome.org.

If you are curious to what it was, you can check it out [here](https://www.bing.com/?FORM=HPSHTW&mkt=en-AU&ssd=20170806_1400).

**Comment by IvanTurgenev** [comment]
It fixed itself when i rebooted the pc

**Comment by neffo** [comment]
Fix is now live on [extensions.gnome.org](extensions.gnome.org).
